name: Build macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup dependencies
        env:
          HOMEBREW_NO_ANALYTICS: 1
        run: brew install sdl2
      - name: Build irisdual
        run: |
          cmake -Bbuild \
            -DCMAKE_CXX_FLAGS="-s" \
            -DSDL2_STATIC=ON \
            -DCMAKE_BUILD_TYPE=Release \
          cd build
          make -j${getconf _NPROCESSORS_ONLN)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: irisdual-${{ runner.os }}
          path: build/bin/sdl/irisdual
          if-no-files-found: error
